export default [
    {
        "name": "object 140",
        "level": 10,
        "armor_penetration": 256,
        "damage": 320,
        "attack_speed": 9.09,
        "time_of_targeting": 2.1,
        "ammunition": 50,
        "country": "USSR",
        "tank_image": "./images/tanks/object_140.png",
        "country_flag":"./images/countries/ussr.png",
        "id": 1
    },
    {
        "name": "conqueror GC",
        "level": 10,
        "armor_penetration": 75,
        "damage": 1150,
        "attack_speed": 1.4,
        "time_of_targeting": 5.5,
        "ammunition": 30,
        "country": "UK",
        "tank_image": "./images/tanks/conqueror_gun.png",
        "country_flag":"./images/countries/uk.png",
        "id": 2
    },
    {
        "name": "e-100",
        "level": 10,
        "armor_penetration": 235,
        "damage": 750,
        "attack_speed": 5.3,
        "time_of_targeting": 2.9,
        "ammunition": 80,
        "country": "Germany",
        "tank_image": "./images/tanks/e-100.png",
        "country_flag":"./images/countries/germany.png",
        "id": 3
    },
    {
        "name": "fv215b",
        "level": 10,
        "armor_penetration": 260,
        "damage": 400,
        "attack_speed": 8.8,
        "time_of_targeting": 1.9,
        "ammunition": 45,
        "country": "UK",
        "tank_image": "./images/tanks/fv215b.png",
        "country_flag":"./images/countries/uk.png",
        "id": 4
    },
    {
        "name": "maus",
        "level": 10,
        "armor_penetration": 248,
        "damage": 490,
        "attack_speed": 7.6,
        "time_of_targeting": 2.3,
        "ammunition": 80,
        "country": "Germany",
        "tank_image": "./images/tanks/maus.png",
        "country_flag":"./images/countries/germany.png",
        "id": 5
    },
    {
        "name": "t57",
        "level": 10,
        "armor_penetration": 240,
        "damage": 400,
        "attack_speed": 8,
        "time_of_targeting": 2.2,
        "ammunition": 36,
        "country": "USA",
        "tank_image": "./images/tanks/t57.png",
        "country_flag":"./images/countries/usa.png",
        "id": 6
    },
    {
        "name": "t62a",
        "level": 10,
        "armor_penetration": 256,
        "damage": 320,
        "attack_speed": 9.09,
        "time_of_targeting": 2.1,
        "ammunition": 50,
        "country": "USSR",
        "tank_image": "./images/tanks/t62a.png",
        "country_flag":"./images/countries/ussr.png",
        "id": 7
    },
    {
        "name": "t110e5",
        "level": 10,
        "armor_penetration": 260,
        "damage": 400,
        "attack_speed": 8.2,
        "time_of_targeting": 2.4,
        "ammunition": 40,
        "country": "USA",
        "tank_image": "./images/tanks/t110e5.png",
        "country_flag":"./images/countries/usa.png",
        "id": 8
    }
]